[package]
name = "maxwell"
version = "4.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[profile.optimized]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = 3